Feature/cele 52
MetaCell/c-elegans-app pull request #15
Opened 2024-07-26 16:18 UTC by Salam-Dalloul

2024-08-02 14:25 UTC, afonsobspinto requested changes

2024-08-02 14:25 UTC, afonsobspinto commented on applications/visualizer/frontend/src/components/CreateNewWorkspaceDialog.tsx
> +      console.error("Failed to fetch datasets", error);
suggestion (non-blocking): @ddelpiano I think it would be nice to have a new card to address how to give feedback for the user to this type of errors. I think an error snackbar would be enough

2024-08-02 14:25 UTC, afonsobspinto commented on applications/visualizer/frontend/src/components/CreateNewWorkspaceDialog.tsx
> +    if (name === "workspaceName" && errorMessage) {
suggestion (non-blocking): We should use a constant here instead of the hardcoded workspace. That constant would be used as well in the TextField. By doing so we only need to change in one place if we decide to change it later.

2024-08-02 14:25 UTC, afonsobspinto commented on applications/visualizer/frontend/src/components/CreateNewWorkspaceDialog.tsx
> +    debouncedFetchNeurons(value, formValues.selectedDatasets);
Cool 👍

2024-08-02 14:25 UTC, afonsobspinto commented on applications/visualizer/frontend/src/components/CreateNewWorkspaceDialog.tsx
> +    <CustomDialog onClose={onCloseCreateWorkspace} showModal={showCreateWorkspaceDialog} title={"Create New workspace"}>
suggestion (non-blocking): new should be lowercased

2024-08-02 14:25 UTC, afonsobspinto commented on applications/visualizer/frontend/src/components/ViewerSettings.tsx
> +const viewers = {
Issue: We should use the ViewerType enum for the keys

2024-08-02 14:25 UTC, afonsobspinto commented on applications/visualizer/frontend/src/components/ViewerSettings.tsx
> +      if (e.target.checked) {
suggestion (non-blocking): I would prefer a slightly different approach in the creation of the widget configurations but I think it's a matter of taste:

```
export const threeDViewerWidget = (status = WidgetStatus.ACTIVE) => ({
  id: widgetIds.threeDViewer,
  name: "3D Viewer",
  component: widgetIds.threeDViewer,
  panelName: "rightPanel",
  enableClose: false,
  status,
});

export const twoDViewerWidget = (status = WidgetStatus.ACTIVE) => ({
  id: widgetIds.twoDViewer,
  name: "Connectivity Graph",
  component: widgetIds.twoDViewer,
  panelName: "leftPanel",
  enableClose: false,
  status,
});

const viewers = {
  Graph: twoDViewerWidget,
  "3D": threeDViewerWidget,
};

const handleToggle = (e, viewer) => {
  const status = e.target.checked ? WidgetStatus.ACTIVE : WidgetStatus.MINIMIZED;
  const selectedViewerFunction = viewers[viewer];
  if (selectedViewerFunction) {
    const viewerConfig = selectedViewerFunction(status);
    dispatch(updateWidget(viewerConfig));
    currentWorkspace.changeViewerVisibility(viewer, e.target.checked);
  } else {
    return;
  }
};

```

2024-08-02 14:25 UTC, afonsobspinto commented on applications/visualizer/frontend/src/contexts/GlobalContext.tsx
> +  datasets: Record<string, Dataset>;
nice 👍

2024-08-02 14:25 UTC, afonsobspinto commented on applications/visualizer/frontend/src/models/workspace.ts
> +    globalContext: GlobalContextType,
issue (blocking): I don't think this is a good idea. If we need to know what datasets exist we should pass only the datasets, not the whole context. Possibly we can replace the     `datasetIds: Set<string>`, with `Record<string, Dataset>` and we avoid the _initializeActiveDatasets all along

2024-08-12 10:39 UTC, ddelpiano approved these changes

2024-08-12 17:31 UTC, aranega commented
@Salam-Dalloul it seems that there is various conficts, could you check?

2024-08-13 12:25 UTC, merged