#70
MetaCell/c-elegans-app pull request #35
Opened 2024-09-06 12:54 UTC by Salam-Dalloul

apply the main neuron selected background style

2024-09-10 12:58 UTC, afonsobspinto requested changes
I think the edge width still needs some work. In the original nemanode the difference in width between f.e. BAG and AFD is much clearer
![image](https://github.com/user-attachments/assets/28889530-6914-4427-ac0e-aca605fd6454)
![image](https://github.com/user-attachments/assets/4c50e1a9-7c72-4309-b137-b3c7f8afdaf7)

2024-09-10 13:48 UTC, Salam-Dalloul commented
> I think the edge width still needs some work. In the original nemanode the difference in width between f.e. BAG and AFD is much clearer ![image](https://private-user-images.githubusercontent.com/19196034/366049052-28889530-6914-4427-ac0e-aca605fd6454.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzYyNDEsIm5iZiI6MTcyNTk3NTk0MSwicGF0aCI6Ii8xOTE5NjAzNC8zNjYwNDkwNTItMjg4ODk1MzAtNjkxNC00NDI3LWFjMGUtYWNhNjA1ZmQ2NDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDEzNDU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5N2Y1YWMxMmQwNWYwNDAwYTBjMGM2N2Q1NWFiOWVmOWVjNjgwYzc4NGU3NzQ5YjQxN2QwNGJmOGYwMzY0ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hFoGgpPTMjdPaurM5fx_hKQsDe16Def5rMylYgzP-bQ) ![image](https://private-user-images.githubusercontent.com/19196034/366049156-4c50e1a9-7c72-4309-b137-b3c7f8afdaf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzYyNDEsIm5iZiI6MTcyNTk3NTk0MSwicGF0aCI6Ii8xOTE5NjAzNC8zNjYwNDkxNTYtNGM1MGUxYTktN2M3Mi00MzA5LWIxMzctYjNjN2Y4YWZkYWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDEzNDU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmODZhOTFmYTFkNTNhZjEyZWJmNTRkOTRjYTk3NDAxODgxYTM2MTAwMmEwODlhZGU3ZjJmYzNkYjkxZTJkN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1GwPjluS3h82kGlYXy7qaPWgGM1LFz8m0BTV9FVCICY)

@afonsobspinto about this part we are still using the synapses length for edge width, the formula that we have to use is still not confirmed, in this PR, the electrical and chemical edges where using a fixed width of .5rem which i just replaced with the width we are passing when creating the edges

2024-09-12 13:43 UTC, ddelpiano approved these changes

2024-09-12 15:04 UTC, afonsobspinto approved these changes

2024-09-13 10:30 UTC, merged